const root=document.documentElement,body=document.body,header=document.querySelector('[data-header]');
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));

const film=document.querySelector('[data-film]');const scenes=[...document.querySelectorAll('[data-scene]')];const frame=document.querySelector('[data-frame]');const dots=[...document.querySelectorAll('.chapter-dots li')];let ticking=false;
function updateFilm(){ticking=false;if(!film||!scenes.length)return;const max=Math.max(1,film.offsetHeight-innerHeight);const progress=clamp(-film.getBoundingClientRect().top/max);const total=Number(film.dataset.total||2400);root.style.setProperty('--progress',progress);if(frame)frame.textContent=String(Math.round(progress*total)).padStart(4,'0');const span=1/scenes.length;scenes.forEach((scene,index)=>{const raw=(progress-index*span)/span,local=clamp(raw);const fadeIn=index===0?1:clamp((raw+.2)/.24),fadeOut=index===scenes.length-1?1:clamp((1.2-raw)/.24),opacity=Math.min(fadeIn,fadeOut);const swallow=1-Math.pow(1-clamp((raw+.2)/.48),3);scene.style.setProperty('--local',local);scene.style.setProperty('--swallow',swallow);scene.style.setProperty('--swallow-radius',`${24+swallow*104}%`);scene.style.opacity=String(opacity);scene.classList.toggle('active',opacity>.015);if(scene.classList.contains('logo-scene')){const finesse=1-Math.pow(1-local,2.35),kick=Math.sin(local*Math.PI)*Math.pow(local,1.7);scene.style.setProperty('--logo-finesse',finesse);scene.style.setProperty('--logo-kick',kick);scene.style.setProperty('--torch',clamp((local-.68)/.32))}scene.querySelectorAll('[data-beat]').forEach((line,lineIndex)=>{const beat=clamp((local-lineIndex*.35)/.3);const fade=lineIndex===0?clamp((.72-local)/.16):1;line.style.opacity=String(beat*fade);line.style.transform=`translate3d(0,${(1-beat)*62}px,0) scale(${.94+beat*.06})`});dots[index]?.classList.toggle('active',local>.08&&local<.95)});header?.classList.toggle('scrolled',scrollY>24)}
function requestFilm(){if(!ticking){ticking=true;requestAnimationFrame(updateFilm)}}addEventListener('scroll',requestFilm,{passive:true});addEventListener('resize',requestFilm);requestFilm();

function filmScrollTarget(progress){const max=Math.max(1,film.offsetHeight-innerHeight);return film.offsetTop+clamp(progress)*max}function settleFilm(){if(!film||root.dataset.motion==='reduced'||!scenes.length)return;const max=Math.max(1,film.offsetHeight-innerHeight),progress=clamp((scrollY-film.offsetTop)/max),span=1/scenes.length;const targets=scenes.slice(0,-1).map((_,index)=>(index+.79)*span);const nearest=targets.reduce((best,target)=>Math.abs(target-progress)<Math.abs(best-progress)?target:best,targets[0]??progress);const distance=Math.abs(nearest-progress);document.querySelector('.film-meta')?.classList.toggle('magnet',distance<span*.07);if(distance>span*.008&&distance<span*.07)scrollTo({top:filmScrollTarget(nearest),behavior:'smooth'})}addEventListener('scrollend',settleFilm);dots.forEach((dot,index)=>{dot.tabIndex=0;dot.setAttribute('role','button');dot.setAttribute('aria-label',`Go to animated chapter ${index+1}`);const go=()=>scrollTo({top:filmScrollTarget((index+.025)/scenes.length),behavior:'smooth'});dot.addEventListener('click',go);dot.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();go()}})});

const menu=document.querySelector('[data-menu]'),nav=document.querySelector('[data-nav]');menu?.addEventListener('click',()=>{const open=body.classList.toggle('nav-open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Close':'Menu'});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{body.classList.remove('nav-open');menu?.setAttribute('aria-expanded','false');if(menu)menu.textContent='Menu'}));

const dialogs=[...document.querySelectorAll('dialog')];function openDialog(dialog){dialog?.showModal();body.classList.add('dialog-open')}function closeDialog(dialog){dialog?.close();body.classList.remove('dialog-open')}document.querySelectorAll('[data-dialog-close]').forEach(button=>button.addEventListener('click',()=>closeDialog(button.closest('dialog'))));dialogs.forEach(dialog=>dialog.addEventListener('close',()=>body.classList.remove('dialog-open')));

const searchDialog=document.querySelector('[data-search-dialog]'),searchInput=document.querySelector('[data-search-input]'),searchResults=document.querySelector('[data-search-results]');const index=[['Home','The 2,400-frame national story','index.html'],['About KOA','History, vision, mission, and coalition','about.html'],['Programs','Civic education, community engagement, and humanitarian assistance','programs.html'],['Stories','Advocacy, culture, sport, and solidarity','stories.html'],['Contact','Email, Messenger, Facebook, and collaboration','contact.html']];function renderSearch(){if(!searchResults)return;const q=(searchInput?.value||'').trim().toLowerCase();searchResults.replaceChildren();index.filter(item=>!q||item.join(' ').toLowerCase().includes(q)).forEach(item=>{const link=document.createElement('a');link.href=item[2];const strong=document.createElement('strong');strong.textContent=item[0];const span=document.createElement('span');span.textContent=item[1];link.append(strong,span);searchResults.append(link)})}document.querySelectorAll('[data-search-open]').forEach(button=>button.addEventListener('click',()=>{openDialog(searchDialog);renderSearch();requestAnimationFrame(()=>searchInput?.focus())}));searchInput?.addEventListener('input',renderSearch);addEventListener('keydown',event=>{const typing=event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement;if(event.key==='/'&&!typing&&!document.querySelector('dialog[open]')){event.preventDefault();openDialog(searchDialog);renderSearch();requestAnimationFrame(()=>searchInput?.focus())}if(event.key==='Escape'&&body.classList.contains('nav-open'))menu?.click()});

const motionButton=document.querySelector('[data-motion]');function setMotion(reduced){root.dataset.motion=reduced?'reduced':'full';motionButton?.setAttribute('aria-pressed',String(reduced));if(motionButton)motionButton.textContent=reduced?'Motion off':'Motion on';localStorage.setItem('koa-motion',reduced?'reduced':'full')}setMotion(localStorage.getItem('koa-motion')==='reduced'||matchMedia('(prefers-reduced-motion: reduce)').matches);motionButton?.addEventListener('click',()=>setMotion(root.dataset.motion!=='reduced'));

const dictionaryInput=document.querySelector('[data-dictionary-input]');const dictionaryCards=[...document.querySelectorAll('[data-dictionary-term]')];dictionaryInput?.addEventListener('input',()=>{const query=dictionaryInput.value.trim().toLowerCase();dictionaryCards.forEach(card=>{card.hidden=Boolean(query&&!card.dataset.dictionaryTerm.toLowerCase().includes(query))})});

const tabButtons=[...document.querySelectorAll('[data-tab]')],tabPanels=[...document.querySelectorAll('[data-panel]')];tabButtons.forEach((button,index)=>button.addEventListener('click',()=>{tabButtons.forEach((item,i)=>{const selected=i===index;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1});tabPanels.forEach((panel,i)=>panel.hidden=i!==index)}));

document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>openDialog(document.querySelector('[data-language-dialog]'))));
